name: MacOS Metal tests

on:
  push:
    branches:
      - main
    paths:
      - "quanto/**"
      - "test/**"
      - "pyproject.toml"
      - "setup.py"
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths:
      - "quanto/**"
      - "test/**"
      - "pyproject.toml"
      - "setup.py"

jobs:
  conventional-commits:
    uses: ./.github/workflows/conventional-commits.yml
  python-quality:
    uses: ./.github/workflows/python-quality.yml
  test-ubuntu-cuda:
    needs: [conventional-commits, python-quality]
    runs-on: [macos-latest-xlarge]
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Build and install quanto
        run: |
          pip install --upgrade pip
          pip install .[dev]

      - name: Run tests
        run: |
          python -m pytest test
